### PR TITLE
add --shallow-submodules to git clone --recursive command in README

### LINKED ISSUE #23: Excessive weight of submodules esp Eigen
The **README** says to do: `git clone --recursive https://github.com/usnistgov/ChebTools` but the fact that Eigen is a submodule is a big negative to this!

The above `clone` command kept failing on my system when trying cloning this submodule because it is a huge repo (see below) and cloning it took a long long time on my village broadband connection and failed half way through (or less) with some obscure TSL broken pipe error or something. Finally I had a friend clone it from a faster connection and send me a ZIP of the repo and included it under the `externals/` directory and only then I was able to do `python setup.py install`.

Then I examined the contents of the cloned **ChebTools** repo:

```bash
$ du -hs chebtools
130M    chebtools
$ cd chebtools
$ du -hs * | sort -h
4.0K    apt.txt
4.0K    CMakeLists.txt
4.0K    environment.yml
4.0K    LICENSE
4.0K    setup.py
4.0K    speed_test.cpp
8.0K    main.cpp
8.0K    README.md
16K     tests
20K     include
20K     scripts
44K     src
104K    Doxyfile
136K    BattlesTrefethen.ipynb
428K    JOSS
110M    externals
$ cd externals/
$ du -hs * | sort -h
2.1M    pybind11
2.3M    Catch
106M    Eigen
```

You can see that for a total of 130M of the repo, 106M are in the underlying Eigen repo. Nobody really needs the whole of the Eigen history unless they are interested in hacking that!

First of all, it is far easier to have the user install Eigen from their distro's packaging system and the submodule is not necessary. Submodules are a convenience shortcut for managing dependencies yes but when they are so heavy it's not so convenient. Installing `libeigen3-dev` on my Kubuntu Bionic system entails only 810k of download compared to the 106M above!

So first of all I would recommend to not use the submodule for this purpose at least for Eigen and instead ask the user to install from their distro.

Even if you want to retain the submodule for convenience, at least you can change the README to suggest to shallowly clone the submodules using `--shallow-submodules`. See [the documentation](https://git-scm.com/docs/git-clone). Doing this makes things much better and I was able to clone on my connection without any problem and the disk usage is also much reduced: 16M vs 106M.

```bash
$ du -hs chebtools--shallow-submodules
30M     chebtools--shallow-submodules
$ cd chebtools--shallow-submodules
$ du -hs * | sort -h
4.0K    apt.txt
4.0K    CMakeLists.txt
4.0K    environment.yml
4.0K    LICENSE
4.0K    setup.py
4.0K    speed_test.cpp
8.0K    main.cpp
8.0K    README.md
16K     tests
20K     include
20K     scripts
44K     src
104K    Doxyfile
136K    BattlesTrefethen.ipynb
428K    JOSS
20M     externals
$ cd externals/
$ du -hsc * | sort -h
2.2M    pybind11
2.3M    Catch
16M     Eigen
```

I confirmed that `python setup.py install` was successful even with the shallow submodule clone.

### PR DESCRIPTION
**Pull request by jamadagni**
Fixes #23. For details see there.

### CODE REVIEW

**Comment by ianhbell** [comment]
Can you remove the whitespace changes?  If not, don't worry.

**Comment by jamadagni** [comment]
Those were automatically done by my editor in cutting out trailing spaces.
I'm traveling now so if you don't want those changes can you please use
your ability to do "edit from maintainers"? Thanks.

**Comment by ianhbell** [comment]
No worries, they are pretty inoffensive whitespace changes.  I’ll merge.

**Comment by ianhbell** [comment]
Thank you!

**Pull request merged**
